version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      time: "20:00"
    commit-message:
      prefix: "chore"
    groups:
      go-modules:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "20:00"
    commit-message:
      prefix: "chore"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "20:00"
    commit-message:
      prefix: "chore"
