DOCKER_CMD ?= docker
DOCKER_REGISTRY ?= ghcr.io
DOCKER_ORG ?= taekjaskyli
PROJECT_NAME ?= kafka-canary
DOCKER_TAG ?= latest
BUILD_TAG ?= latest
VERSION ?= dev

IMAGE := $(DOCKER_REGISTRY)/$(DOCKER_ORG)/$(PROJECT_NAME)

.PHONY: docker_build
docker_build:
	echo "Building Docker image ..."
	${DOCKER_CMD} build --build-arg VERSION=$(VERSION) -t $(IMAGE):$(BUILD_TAG) .
	${DOCKER_CMD} tag $(IMAGE):$(BUILD_TAG) $(IMAGE):$(DOCKER_TAG)

.PHONY: docker_push
docker_push:
	echo "Pushing Docker image ..."
	${DOCKER_CMD} push $(IMAGE):$(DOCKER_TAG)
