BINARY ?= kafka-canary
RELEASE_VERSION ?= dev

.PHONY: go_build
go_build:
	echo "Building Golang binary for ${RELEASE_VERSION}..."
	GOTOOLCHAIN=local CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -X 'main.version=${RELEASE_VERSION}'" -o cmd/target/$(BINARY) ./cmd/

.PHONY: go_clean
go_clean:
	echo "Cleaning Golang binary ..."
	rm -rf cmd/target
